### ISSUE TITLE
social media task: social approval score

### ISSUE THREAD

**Issue by toujames** [laureate-institute-for-brain-research/StimToolOnline#12]
We could just shift social approval up artificially. Just add 30% or something to the calculated, or whatever could get them up to like 90% theoretically but never over 100%. We could also add something on the side that says Chatroom participants: 100 to make that salient.

**Comment by LavalleyCA** [comment]
So, scratch the current social approval score. Moving to an individual score after each chatroom (green social approval score that is percentage of likes out of possible likes, red social disapproval score that is percentage of dislikes out of possible dislikes). There is no summation of these scores, games are considered completely independent. (This should fix the wonky -50% stuff and some other issues Ryan, Sam and I came up with when chatting just now)

**Comment by toujames** [comment]
I see so there's 2 score we show now

## 1) Green Social Approval
What we calculate currently with likes

## 2) Red Social Disapproval
Percentage of dislikes out of possible dislikes.

**Comment by LavalleyCA** [comment]
But they only show up at the end of each game (all 5 or ten trials in a chatroom) and disappear at the start of the next game. So there's no more overall score just per chatroom

**Comment by toujames** [comment]
**Applied**
![Screen Shot 2022-07-20 at 1 56 20 PM](https://user-images.githubusercontent.com/7041040/180063758-608676f2-29b3-4e14-bfba-c4dbda5f60b8.png)
![Screen Shot 2022-07-20 at 1 57 23 PM](https://user-images.githubusercontent.com/7041040/180063761-fa193f17-45ee-41ff-8a64-a39f1a9f4b0f.png)


- Social Approval Score is calculated by total likes they got out of the possible likes (100 per post)
  - Green Text in the screen
- Social Disapproval Score is calculated by total dislikes they got out of possible dislikes (100 per post)
  - Red Text on the screen

The score screen only shows after each chatroom and only shown for **3** seconds.

**Comment by LavalleyCA** [comment]
I like it!

**Comment by toujames** [comment]
The sidebar looks like this now as well.
![Screen Shot 2022-07-20 at 2 21 43 PM](https://user-images.githubusercontent.com/7041040/180064776-ccb249fd-b4a2-48fc-b316-2d2d8a34e0fe.png)
