### ISSUE TITLE
blind dating game update

### ISSUE THREAD

**Issue by rssmith33** [laureate-institute-for-brain-research/StimToolOnline#15]
I think I want to change the images we use to indicate the possible blind dates to something more like the following, where the surround of each one lights up from left to right. We can use the male/female depending on the person's stated preference.  

![image](https://user-images.githubusercontent.com/49658036/180879452-22dd7a1a-0a97-4083-839f-ae909279d3ef.png)

![image](https://user-images.githubusercontent.com/49658036/180879530-1de098f3-477b-4f78-a59c-1366260787d9.png)

Also, here's a set of questions to ask about.

Please answer the following questions to let us know what you are looking for in a partner.

Is your desired partner male or female?

Would you prefer they be short, medium height, or tall? How important is this to you on a scale from 1 - 10?

Would you prefer they be in good athletic shape? How important is this to you on a scale from 1 - 10?

Would you prefer they be messy or organized? How important is this to you on a scale from 1 - 10?

Do you prefer a partner that likes to go on relaxing vacations or active vacations? How important is this to you on a scale from 1 - 10?

How important is it to you that your partner has a high income? How important is this to you on a scale from 1 - 10?

Do you have a preferred hair color for a partner? How important is this to you on a scale from 1 - 10?

How important that your partner be religious on a scale from 1 - 10? Please enter a specific religion if this is important to you.

Is there any other important preference you'd like to add?

**Comment by toujames** [comment]
Note - have a question about gender preference and use that to show the correct gender.

**Comment by toujames** [comment]
Updated the images on commit [3031bc4](https://github.com/laureate-institute-for-brain-research/StimToolOnline/commit/3031bc4b58e11e63bec4157e3b0a965b75f4e6a4)

Looks like this:
![Screen Shot 2022-08-04 at 6 27 56 PM](https://user-images.githubusercontent.com/7041040/182971953-434f6f65-6296-4b7b-be63-d8c77784d234.png)
