### ISSUE TITLE
Social media task - new issues

### ISSUE THREAD

**Issue by rssmith33** [laureate-institute-for-brain-research/StimToolOnline#24]
The last window still says they win 5 cents. Remove this.

In approximately 5 chatrooms, some tweets were NAs (usually near the end). Make sure all posts have text.

When you choose to go backward in the instructions, right now it makes you listen to the whole recording again before you can go forward. Make it so it only plays the recording the first time you go to a slide. If you go backward, it shouldn't play the instructions again or have a delay for them to go forwards.

Also, just a heads up - when Phil did it it took him an hr, while the Horizon task took only 15 min. So hopefully we can find ways to make it go faster. If you have any ideas...

**Comment by toujames** [comment]
Fixed NA issue by adding more tweets to Cats and Spelunking:

Commit ID: 2474e46

Closing this for now as the issues have been all addressed. Unless if the issure are still there

**Comment by a-chuning** [comment]
Hi! 
Eric's feedback indicated that there are NA's still for chat room 77 and chat room 79... 

Chat room 77: Woodworking - started to give "NA" as responses after selecting a few times
Chat room 79: Botany - started to give "NA" as responses after selecting a few times

**Comment by toujames** [comment]
Thanks Annie!

Just looked into this.
The tweets are updated on this git repo, but the changes never got push to the production machine.

**Comment by a-chuning** [comment]
Okay, great!! Also, I made some proofreading edits to a number of the tweets in the excel sheet online yesterday. Will those also update into the newest version?

**Comment by toujames** [comment]
That's correct. see commit id: 4959c42
The new version will have those tweets you made.
