### ISSUE TITLE
Small typos on instruction slides

### ISSUE THREAD

**Issue by 0xSMT** [laureate-institute-for-brain-research/StimToolOnline#25]
On the below slide, the instructions should say "chatroom" instead of "chatrooms":
<img width="1080" alt="Screen Shot 2022-08-08 at 11 44 28 AM" src="https://user-images.githubusercontent.com/19697136/183471450-ec2ab9c0-20a6-4a0b-8205-d402050bb84a.png">

On the below slide, the instructions should say "drops" instead of "drop" (to align with the audio as well):
<img width="1080" alt="Screen Shot 2022-08-08 at 11 45 02 AM" src="https://user-images.githubusercontent.com/19697136/183471482-c6522ef5-4957-4b6d-ac6c-758e2d0fe297.png">

**Comment by toujames** [comment]
Thanks. Fixed the typos.

Slide 27 and Slide 28 updated.
