### ISSUE TITLE
Failed to start task

### ISSUE THREAD

**Issue by 0xSMT** [laureate-institute-for-brain-research/StimToolOnline#27]
After trying to start task, this error appeared (while resources were being downloaded at the start):
<img width="1080" alt="Screen Shot 2022-08-09 at 1 36 24 PM" src="https://user-images.githubusercontent.com/19697136/183735758-6ac65fed-898b-4ed2-89ea-ab9af633ef95.png">

Not sure it's too important, restarting seemed to work, but happened a couple times.

**Comment by toujames** [comment]
depending on when you played it, I might've restarted the application.

Try refreshing the page?

**Comment by 0xSMT** [comment]
Yeah I'm going through the task now, doesn't seem to be a crippling issue or anything, might have been a once-off problem

**Comment by toujames** [comment]
yeah, most likely, Usually if it's a "download resources" error, its most likely because, i'm simlutaneously updating the application or it just has har time pulling the data from the virtual machine.

I'm closing the issue, - unless if it comes up again.
