### ISSUE TITLE
NAs in Botany and Woodcarving (at least)

### ISSUE THREAD

**Issue by 0xSMT** [laureate-institute-for-brain-research/StimToolOnline#29]
Attached below are some NAs I observed (might be more categories, especially in the H1 trials where I can't check each topic after the four forced trials):

<img width="1398" alt="Screen Shot 2022-08-09 at 2 33 07 PM" src="https://user-images.githubusercontent.com/19697136/183745990-3b1ed458-82b0-459f-a891-d45d0e9e3575.png">
<img width="1398" alt="Screen Shot 2022-08-09 at 2 34 05 PM" src="https://user-images.githubusercontent.com/19697136/183745996-9839c8b4-eeb6-4d68-a8f8-78206efc652f.png">
:

**Comment by toujames** [comment]
I'm creating a script to count the NA on each H6 trials, hope fully it'll show which topics still need more tweets.

**Comment by toujames** [comment]
Ran the script found these additional topics:

- Classical Music
- DJing

**Comment by toujames** [comment]
Updated tweets. On commit id 395bacb
