### ISSUE TITLE
Different aesthetics in different modes

### ISSUE THREAD

**Issue by 0xSMT** [laureate-institute-for-brain-research/StimToolOnline#30]
In the mode where you have two rooms to choose to like a tweet or not (screenshot below), the style of the surrounding panes is different from the real game (also screenshot below). The "liking" mode is monochromatic in the panes and participant avatar.
<img width="1398" alt="Screen Shot 2022-08-09 at 1 42 31 PM" src="https://user-images.githubusercontent.com/19697136/183746469-88020920-1a26-4636-a415-3793a63427c3.png">
<img width="1398" alt="Screen Shot 2022-08-09 at 1 50 51 PM" src="https://user-images.githubusercontent.com/19697136/183746479-7a5c7820-4220-46bc-aa9b-49daa13eef24.png">

**Comment by toujames** [comment]
Yeah, the role reversal portion, it's supposed to be monochromatic since the 'participant' is a different user. 

Hope i understand that correctly?

**Comment by toujames** [comment]
Closing ticket. Profile image is now in color as well.

![Screen Shot 2022-08-15 at 8 43 39 PM](https://user-images.githubusercontent.com/7041040/184781112-c758ef37-3984-422b-8cec-0090a383a01b.png)
