### ISSUE TITLE
Updated social media task slides

### ISSUE THREAD

**Issue by rssmith33** [laureate-institute-for-brain-research/StimToolOnline#33]
[Social_media_task_instructions_08_11_2022.pptx](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/9309969/Social_media_task_instructions_08_11_2022.pptx)

**Comment by toujames** [comment]
Was there any significant changes in terms of wording or was it mostly typos and stuff?
- If there are, we have to re-record the audio

**Comment by rssmith33** [comment]
I mostly just added underlining and things like that. But I did alter wording in a couple places. I'll figure out which slides and we can re-record.

I also had a conversation with Bob, who designed the horizon task, to ask about possible ways to shorten. He suggested we change Horizon 6 into Horizon 5, so there's one less choice for every H6 game (he said they've done some studies showing it doesn't really change anything). Then I'd need to change whatever slides say "10 choices" into "9 choices". Would it be very time consuming to cut one tweet spot off the end for H6 to become H5?

Best,

Ryan
________________________________

**Comment by toujames** [comment]
To change to h5 from h4. From my end, not really.
Would ave to edit the schedule file and remove all trial number 9. 
(in the schedule file, trial numbering starts at 0)

@LavalleyCA - looping so that you know that you may have to re-record some slides.

**Comment by rssmith33** [comment]
Just to make sure, it would be removing trial 10, not trial 9.

Best,

Ryan
________________________________

**Comment by toujames** [comment]
Yes, that's correct - trial numbering starts at 0.
> (in the schedule file, trial numbering starts at 0)

**Comment by rssmith33** [comment]
Ah, got it.

Best,

Ryan
________________________________

**Comment by rssmith33** [comment]
Here's further updated slides (8_12) for the social media task, which changed all the H6's to H5's.

This requires cropping a few pictures, and re-recording a few more slides.

Best,

Ryan
________________________________

**Comment by toujames** [comment]
Think you may have forgotten to attach the powerpoint slides...

**Comment by rssmith33** [comment]
[Social_media_task_instructions_08_12_2022.pptx](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/9329398/Social_media_task_instructions_08_12_2022.pptx)

**Comment by rssmith33** [comment]
I attached it, but through email, so it might not have gone through. I did it directly in the issue now.

Best,

Ryan
________________________________

**Comment by toujames** [comment]
Thanks. Got it. and Updated.
Commit ID: 380e9b9

**Comment by toujames** [comment]
Just for the record. we're waiting for new audio recordings. I'll close this ticket once it's been updated.

**Comment by LavalleyCA** [comment]
Updated task instruction recordings - [SocialMediaTaskInstructions_8_17_22.zip](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/9363292/SocialMediaTaskInstructions_8_17_22.zip)

**Comment by LavalleyCA** [comment]
Updated task instruction recordings - [SocialMediaTaskInstructions_8_17_22.zip](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/9363369/SocialMediaTaskInstructions_8_17_22.zip)

Same as before (and with speed dating), the number _n_ on each audio recording corresponds to the _n+1_ slide in the instructions.

**Comment by LavalleyCA** [comment]
Most recent slides that correspond with time-stamped audio recording zip file -
[Social_media_task_instructions_08_17_2022.pptx](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/9363451/Social_media_task_instructions_08_17_2022.pptx)

**Comment by toujames** [comment]
Updated the slides and audio. Thanks.
