### ISSUE TITLE
Speed Dating Updates from Lab Meeting

### ISSUE THREAD

**Issue by LavalleyCA** [laureate-institute-for-brain-research/StimToolOnline#34]
Heyo, 
Some notes from lab meeting:

- On the slide where it shows what happens when you accept a person and it says "YOU HAVE A DATE", Ryan would like to had an exclamation point (I think there's an exclamation point in the real 
- In the preferences, when people are choosing how important something is, it should be clarified that 10 is most important. (ie. 1-not important at all, 10-extremely important)
- In the practice session, the example percentages should be taken from the limited offer schedule because right now the matches are all pretty low (12%, 7%, 9%). 
- I'm actually going to create and send to you an updated schedule to feed in for the low offers because we have a new idea for values and also the high value offer will be >90.

Should be all for now :) Thanks!

**Comment by toujames** [comment]
Can you send the updated practice schedule as well?

**Comment by LavalleyCA** [comment]
Not sure if you still needed this - [speed_dating_schedule.csv](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/9352334/speed_dating_schedule.csv)

**Comment by LavalleyCA** [comment]
Task Instructions - [SpeedDatingTaskInstructions.zip](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/9352847/SpeedDatingTaskInstructions.zip)

**Comment by toujames** [comment]
You skipped slide 15:
![Slide15](https://user-images.githubusercontent.com/7041040/185529264-585ae123-0aa5-4893-9267-65cb00ce6a64.jpeg)

**Comment by LavalleyCA** [comment]
Most updated recordings - [SpeedDatingTaskInstructions_8_19_22.zip](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/9384597/SpeedDatingTaskInstructions_8_19_22.zip)

**Comment by LavalleyCA** [comment]
Most updated instruction slides - [Blind_dating_game_instructionsV4.pptx](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/9384787/Blind_dating_game_instructionsV4.pptx)

**Comment by LavalleyCA** [comment]
Bonjour, We had someone test out this task and there are some notes:

- Looks like the newest version of the instructions isn't in there yet (see above, V4)
- "... I noticed that the event number occasionally resets back to 1/108. I took a screenshot after I noticed where my total number of dates is higher than the event number shown and then it seemed like I successfully finished a few runs later as it just said "Thank you for your patience" and brought me to a starting page for the emotional faces task." (See the image)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/109167492/186505858-49e0722b-5045-454c-8bfc-56c511254489.png)

**Comment by toujames** [comment]
Fixe the issues and updated the slides and audio.
