### ISSUE TITLE
Emotional Face Recognition - schedule

### ISSUE THREAD

**Issue by LavalleyCA** [laureate-institute-for-brain-research/StimToolOnline#35]
!H (hi upside down),
I have the schedule for the faces task for ya:
[main_faces_schedule.csv](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/9418912/main_faces_schedule.csv)

**Comment by toujames** [comment]
Thanks.
Me and Ryan went over the schedule - hoping you could generete the name of the faces on your end?

**Comment by LavalleyCA** [comment]
Here is the schedule with the file paths: [main_faces_schedule.csv](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/9491106/main_faces_schedule.csv)

**Comment by LavalleyCA** [comment]
Here's the schedule with the file paths to the faces: [main_faces_schedule.csv](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/9491113/main_faces_schedule.csv)

**Comment by toujames** [comment]
Thanks.
Updated the schedule.
Use this link to test it out:

https://tasks.laureateinstitute.org/?index=2&task=emotional_faces&run=Pilot_R1.json

**Comment by LavalleyCA** [comment]
The for real for real schedule with 50/50 gender split:
[faces_schedule_9_15_22.csv](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/9574643/faces_schedule_9_15_22.csv)

**Comment by toujames** [comment]
Updated. with new task from 9/15/2022
