### ISSUE TITLE
Speed dating game: length of screen showing "YOU HAVE A DATE" or "END UP ALONE"

### ISSUE THREAD

**Issue by nate-libr** [laureate-institute-for-brain-research/StimToolOnline#38]
After each event, it will show "YOU HAVE A DATE" or "END UP ALONE".  It lasts for approximately 4-5 seconds.  Could you please reduce that to 2 seconds.

**Comment by toujames** [comment]
Issue fixed on commit [0d67639](https://github.com/laureate-institute-for-brain-research/StimToolOnline/commit/0d67639a070e63e5b29b929a86c772e8653db206)
