### ISSUE TITLE
Emotional Faces -- Growing White Squares

### ISSUE THREAD

**Issue by 0xSMT** [laureate-institute-for-brain-research/StimToolOnline#41]
During the actual task, if you keep pressing the right or left button on a given round, the white box around "Angry" or "Sad" continues to grow, and this size increase persists between trials.

**Comment by toujames** [comment]
Thanks.

FIxed on commit  
8615fb5

Solution was to not allow a user to enter multiple presses. This was one of the points discussed last Friday.
