### ISSUE TITLE
Emotional faces - incorrect feedback

### ISSUE THREAD

**Issue by rssmith33** [laureate-institute-for-brain-research/StimToolOnline#42]
In the beginning of the task when they go through the faces once and are shown 'correct' and 'incorrect', it currently doesn't make them try again if they get it incorrect. When we talked about this last, I believe we said that it would need to wait until they make the correct choice before moving to the next face.

So can it please be changed so that, whenever they make an incorrect choice, it instead says "Incorrect. Try again." and then it will wait for them to make the correct choice before it moves to the next face?

**Comment by toujames** [comment]
Sure, updated on commit [43582fc](https://github.com/laureate-institute-for-brain-research/StimToolOnline/commit/43582fc7514b11e8b8d9dc5dd4c9a6dc9cfa4a9d).

I'm closing the issue, if it's not the way you had in mind. - just respond to the issue, and i'll reopen this issue.
