### ISSUE TITLE
all tasks - still says thank you for your patience

### ISSUE THREAD

**Issue by rssmith33** [laureate-institute-for-brain-research/StimToolOnline#45]
When I hit escape or finish any of the tasks, it still says "thank you for your patience". It should instead say "Thank you for your participation."

**Comment by toujames** [comment]
Changed all those texts in [851d729](https://github.com/laureate-institute-for-brain-research/StimToolOnline/commit/851d729ae18df69d0538f1f65caf3b9b6b5f2346).
