### ISSUE TITLE
Emotional Faces - Instruction Recordings and New Slides

### ISSUE THREAD

**Issue by LavalleyCA** [laureate-institute-for-brain-research/StimToolOnline#46]
Hola,
Here are the most updated slides: [Emotional_Faces_Instructions_9_9_22.pptx](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/9537933/Emotional_Faces_Instructions_9_9_22.pptx)

And here are the recordings: 
[FacesTaskInstructions.zip](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/9537936/FacesTaskInstructions.zip)

Thanks!

**Comment by toujames** [comment]
updated. thanks!
