### ISSUE TITLE
Cooperation Task Updates 10-25-22

### ISSUE THREAD

**Issue by LavalleyCA** [laureate-institute-for-brain-research/StimToolOnline#54]
Ho ho ho,

Here are the two things for the cooperation task:
1) Try 1.5x speed for the images to shorten the overall task,
2) Pseudo-randomize the game order (to not have blocks of 20 positive and then 20 negative).

*thumbs up*
Claire

**Comment by toujames** [comment]
yo yo yo,

This is updated. and is now in production.

_thumbs up_
