### ISSUE TITLE
Updated text during cooperation task

### ISSUE THREAD

**Issue by rssmith33** [laureate-institute-for-brain-research/StimToolOnline#56]
After a participant chooses a person, we would like text to appear under the chosen picture, before it switches to show the image. 

In the positive outcome games, the text would say "Sure, I'll help!" if the positive image will appear, and it will say "Too bad!" if the scrambled image will appear. 

In the negative outcome games, the text would say "Sure, I'll help!" if the scrambled image will appear, and it will say "Too bad!" if the negative image will appear. 

The separate screen saying "insert text here" before each image is shown should be removed.

Also, at the bottom of the screen in the positive outcome games, we'd like text added saying: "You will be shown the meaningless image unless the person you choose decides to help you".

At the bottom of the screen in the negative outcome games, we'd like text added saying: "You will be shown the unpleasant image unless the person you choose decides to help you".

**Comment by toujames** [comment]
Addressed  all these changes on 
485d99c

Closing Issue
