### ISSUE TITLE
Cooperation task game order and game/trial counts

### ISSUE THREAD

**Issue by rssmith33** [laureate-institute-for-brain-research/StimToolOnline#57]
When we just played it, we had 3 or 4 positive outcome games in a row before getting a negative outcome game. This felt like a lot, especially in the beginning. 

I think it's probably better to just have it alternate from positive game to negative game to positive game, etc.

Also, can the counts on the top show the number they're out of? So the game would say 1/20, 2/20, etc. and the trial number would be 1/16, 2/16, etc.

Also, can we change "Trial Number" to "Choice Number"?

**Comment by toujames** [comment]
- Alternated the games 34af8be3adc353759030c3bd19f1b8a4c7c458e9
- Show total games & choice 01d557654448b1584d2e1c75d052f88ef758d274
- "Trial Number" -> "Choice Number" 01d557654448b1584d2e1c75d052f88ef758d274
