### ISSUE TITLE
Cooperation 

### ISSUE THREAD

**Issue by LavalleyCA** [laureate-institute-for-brain-research/StimToolOnline#58]
Let's cooperate!

Anyway, I have new instructions slides for you and some cooperation task updates:
- In the game rooms, we'd like to move the words that say "You will be shown unpleasant/meaningless images unless the person you choose decides to help you" up a bit closer to the faces, have them appear larger, and have the word "unpleasant" be in red (as in previous slides) and the word "meaningless" be white and underlined. (There is an example of this in the updated slides below)

I'll send along audios for this (and faces task) asap!
Thanks

[Cooperation_Task_Instructions.11.2.2022.pptx](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/9924053/Cooperation_Task_Instructions.11.2.2022.pptx)

**Comment by LavalleyCA** [comment]
Audio!
[CooperationTaskInstructions.zip](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/9924259/CooperationTaskInstructions.zip)

**Comment by LavalleyCA** [comment]
Audio! As with the cooperation task, audio clips are now matched with their corresponding instruction slide. (e.g. Audio clip 2 goes with Slide number 2. There is no audio for slide 1)

[FacesTaskInstructions2.zip](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/9924344/FacesTaskInstructions2.zip)

**Comment by toujames** [comment]
Great. Thanks! just updated and on the server.

**Comment by LavalleyCA** [comment]
Hello, I'm opening back up this issue because we would still like to make the change above where, inside the game rooms, the text at the bottom of the screen is increased in size and the words "unpleasant", "pleasant", and "meaningless" are colored/underlined as appropriate. (Red for unpleasant, green for pleasant, underlined for meaningless)

Thanks!
