### ISSUE TITLE
Well-Being Assessment survey code for MTurk

### ISSUE THREAD

**Issue by LavalleyCA** [laureate-institute-for-brain-research/StimToolOnline#74]
This is another survey that will be put onto MTurk with the task, demographic survey, and INDCOL survey. I've attached a text document with the full Java(?) code as well as the embed script code that I had sent for the other surveys. Not sure what's easier so I included both
[Well-Being Assessment.txt](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/10239765/Well-Being.Assessment.txt)
[wba_embed_script.txt](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/10239767/wba_embed_script.txt)

**Comment by toujames** [comment]
would this survey be done after the demographics survey?

**Comment by toujames** [comment]
Link:
https://tasks.laureateinstitute.org/?index=1&survey=well_being&session=1
