### ISSUE TITLE
MTurk Feedback Survey

### ISSUE THREAD

**Issue by LavalleyCA** [laureate-institute-for-brain-research/StimToolOnline#75]
Heyo, new survey to put on MTurk after they finish whichever task they just did. (Two styles of code again bc idk what was easier for you)

[feedback_survey.txt](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/10261515/feedback_survey.txt)
[feedback_survey_embed_code.txt](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/10261516/feedback_survey_embed_code.txt)

**Comment by toujames** [comment]
Added.

https://tasks.laureateinstitute.org/?survey=feedback

**Comment by toujames** [comment]
and, either styles of code is fine. thanks for the thought tho.
