### ISSUE TITLE
Invitation Game Schedule and Details

### ISSUE THREAD

**Issue by LavalleyCA** [laureate-institute-for-brain-research/StimToolOnline#78]
Hello, (This is mostly for James, but Aardron is welcome to participate)
In the Wednesday meeting this week, Ryan and I will explain the following details more. Here's also a schedule for the invitation game. I thought this would help in understanding the info I'm about to share about the game. Not sure if this is all the information you will need in the schedule yet, but this is what we'll start with. 

The schedule includes a "module" column. We are planning on having three parts to this task (and the order might switch so if you can pre-plan for that, it might make things easier in the end). In module 1, participants start in position 1 of either building and make free decisions (depth=3). In module 2, participants start in one box and are given a single move (depth=1) to see how many points they will win in the next room. Th order of this part is determined by the schedule. In module 3 (aka the "planning period"), participants start in position 1 in either an OLL or ONLL trial (similar to the planning task). 

[invitation_schedule.csv](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/10282531/invitation_schedule.csv) ---- Updated 12/21/22

This image shows how the rooms should be connected. Left doors will always be orange, right will be blue. When we have the final list of images, I'll send you those labeled in accordance with the numbering in this chart (e.g., lib_2, lib_3, or office_2, office_3).

<img width="625" alt="flow_chart" src="https://user-images.githubusercontent.com/109167492/208786882-e717b01e-93cc-4be6-ac42-7672003f186c.PNG">

I know this is a lot of info and we'll go over it tomorrow but here's your heads up!

**Comment by toujames** [comment]
thanks. yeah, this helps a ton.

**Comment by toujames** [comment]
This has been updated.
