### ISSUE TITLE
Invitation Game Media

### ISSUE THREAD

**Issue by LavalleyCA** [laureate-institute-for-brain-research/StimToolOnline#81]
Heyo, 

Here is a powerpoint presentation with a pair of slides per room. They are labeled "Lib_2" or "Office_2" so that you know where they go in the tree but those labels shouldn't actually be included in the slides/images. I can turn them into PNGs myself if that would be easier for you, but we weren't sure if you would need to make formatting changes and PNGs would limit you. Let me know!
[Invitation-game_slides-1-24-23.pptx](https://github.com/laureate-institute-for-brain-research/StimToolOnline/files/10500826/Invitation-game_slides-1-24-23.pptx)

Sincerely from the bottom of my heart,
Claire

**Comment by toujames** [comment]
updated. changed on [58ac312](https://github.com/laureate-institute-for-brain-research/StimToolOnline/commit/58ac3127a6066b911bed030f0332fb27b781e0e4)
