### ISSUE TITLE
Social Media Task: not full screen, tweet display

### ISSUE THREAD

**Issue by LavalleyCA** [laureate-institute-for-brain-research/StimToolOnline#9]
When I open the task, it opens like a tab and stays that size. Anyway it could fill the whole screen in like a new window? Also, in the practice slides (on the 3rd one) there's a tweet display issue with the 3rd tweet. It gets cut off.

**Comment by toujames** [comment]
Not making full screen was intentional. But I guess we can change that if we should.
Can you post a screen shot? Of the missing 3rd tweet in the practice slide?
I"m not seeing it.

**Comment by LavalleyCA** [comment]
![social media task issue](https://user-images.githubusercontent.com/109167492/178558217-48056494-3086-47ab-8fc3-1266f5afdff3.jpg)

**Comment by toujames** [comment]
Just reduced it so that it will animate the text in 1 less frame. Just tested this out  and doesn't look like it's showing this bug anymore. Can you try again?

**Comment by LavalleyCA** [comment]
![social media task issue](https://user-images.githubusercontent.com/109167492/180066831-2919ee53-3b61-4a86-bd30-2bd0f8e3236b.jpg)

**Comment by LavalleyCA** [comment]
<img width="806" alt="SocialMediabug" src="https://user-images.githubusercontent.com/109167492/180066893-8e77ae85-2164-4175-bfde-31943f8bb6fd.PNG">

**Comment by toujames** [comment]
Issue tested on Edge. Edge doesn't show the bug.
Although using Chrome seems to be the workaround.
